from .base_annotation_definition import BaseAnnotationDefinition
from .box import Box
from .classification import Classification
from .comparison import Comparison
from .ellipse import Ellipse
from .point import Point
from .polygon import Polygon
from .polyline import Polyline
from .segmentation import Segmentation
from .subtitle import Subtitle
from .undefined_annotation import UndefinedAnnotationType
